name: slip39
description: The dart implementation of the SLIP39 for Shamir's Secret-Sharing for Mnemonic Codes.
version: 1.0.0
author: Pal Dorogi "ilap"<pal.dorogi@gmail.com>
homepage: https://github.com/ilap/slip39-dart

dependencies:
  pointycastle: ^3.0.1
  hex: ^0.2.0
  test:

environment:
  sdk: '>=2.12.0 <3.0.0'
